version: "2.4"
services:
  bitcoinbet:
    build:
      context: .
      dockerfile: bitcoinbetDockerfile
    links:
      - mongodb
      - redisdb
    ports:
      - "5000:5000"
    restart: always
#    env_file:
#      - .env.dev
  mongodb:
    build:
      context: .
      dockerfile: mongoDockerfile
    ports:
     - "27020:27017"
    restart: always
  redisdb:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
#    volumes:
#      - ./data:/data
    restart: always
  flower:
    image: mher/flower:0.9.5
    command: ["flower", "--broker=redis://redisdb:6379/0", "--port=8888"]
    ports:
      - 8888:8888
    links:
      - redisdb
    restart: always