# -*- coding: UTF-8 -*
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
print parentdir[:-5]
sys.path.insert(0,parentdir[:-5])
from mongoengine import *
import datetime
import Settings.settings

_sett = Settings.settings.Settings()
_raw_mongo = _sett.get_mongo
connect(_raw_mongo['db'], host=_raw_mongo['host'], port=_raw_mongo['port'], username=_raw_mongo['user'],
		password=_raw_mongo['pwd'], authentication_source="admin")

class Bets(Document):
	bet_id = StringField(required=True)
	player_id = StringField(required=True)
	#game_id = StringField(required=True)
	amount_bet = DecimalField(required=True, precision=3)
	amount_win = DecimalField(required=True, precision=3)
	initial_balance = DecimalField(required=True, precision=3)
	date = DateTimeField(default=datetime.datetime.utcnow)
	extra = StringField(required=True)
	result = StringField(required=True)
	currency = StringField(required=True)


class Transactions(Document):
	casino_bet_id = StringField(required=True)
	bet_id = StringField(required=True)
	type = StringField(required=True)
	final_balance = DecimalField(required=True, precision=3)
	date = DateTimeField(default=datetime.datetime.utcnow)
	status = StringField(required=True) #success  / failure

class Tokens(Document):
	token = StringField(required=True)
	casino_player_id = StringField(required=True)
	status = StringField(required=True) #Active, Expired
	#game_id =

class Games(Document):
	game_id = IntField(required=True)
	name = StringField(required=True)

# class Coins(Document):
# 	coin_id = IntField(required=True)
# 	name = StringField(required=True)
# 	code = StringField(required=True)
# 	symbol = StringField(required=True)

class Platforms(Document):
	platform_id=StringField(required=True)
	hostname = StringField(required=True)
	getbalance_url = StringField(required=True)
	setbet_url = StringField(required=True)
	developer_id = StringField(required=True)
	#prefix = StringField(required=True)
	#api_url = StringField(max_length=100, required=True)
	#main_url = StringField(required=True)
	key = StringField(required=True)
	casino_home_url = StringField(required=True)
	client_id = StringField(required=True) #UNIQUE FOR EACH CASINO (GENERATED BY RGTSLOTS)
	idgame = StringField(required=True)#UNIQUE UUID FOR EACH PLATFORM (GENERATED BY GAME)
	configuration = StringField(required=True)#BET_MULTIPLIER, BET_MIN, BET_MAX

class Players(Document):
	player_id = StringField(required=True)
	casino_player_id = IntField(required=True)
	platform_id = StringField(required=True)
	tokens = StringField() #{"USD":"TOKEN", "MBTC":"TOKEN"}
	#username = StringField(required=True)

# class CoinKeys(Document):
# 	platform_id = IntField(required=True)
# 	coin_id = IntField(required=True)
#
#
# class Coins(Document):
# 	name = StringField(max_length=50, required=True, primary_key=True)
# 	code = StringField(max_length=50, required=True)

# class Credentials(Document):
# 	platform_name = StringField(max_length=50, required=True)
# 	platform_key = StringField(max_length=50, required=True)
# 	coin = StringField(max_length=50, required=True)

# class Games(Document):
# 	name = StringField(max_length=50, required=True)
# 	category = StringField(max_length=50, required=True)





